"""Add topic

Revision ID: 2b61267d0670
Revises: ac79f8f014b0
Create Date: 2025-03-01 00:57:36.743433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b61267d0670'
down_revision: Union[str, None] = 'ac79f8f014b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('topic_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'courses', 'topics', ['topic_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'topic_id')
    # ### end Alembic commands ###
