"""Add fav course

Revision ID: e3ccc273faac
Revises: 2b61267d0670
Create Date: 2025-03-01 01:02:37.556723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3ccc273faac'
down_revision: Union[str, None] = '2b61267d0670'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fav_courses',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'course_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fav_courses')
    # ### end Alembic commands ###
